### ISSUE TITLE
POST-ing data from svelte to django

### ISSUE THREAD

**Issue by maxdobeck** [thismatters/django-svelte#1]
Just want to triple check, there's no way to POST data from a svelte app without setting up the REST API django side? I don't see an easy way to write a simple server-side form.

https://github.com/thismatters/django-svelte-demo/blob/master/svelte/src/PostComponent.svelte

New to django but thanks for writing this component!

**Comment by thismatters** [comment]
A standard Django view can accept POST data. See [FormView](http://ccbv.co.uk/projects/Django/3.1/django.views.generic.edit/FormView/#post) as an example. I do, however, recommend using Django Rest Framework for handling interaction with a Svelte frontend.

**Comment by maxdobeck** [comment]
Thank you! Makes sense
