### ISSUE TITLE
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

### ISSUE THREAD

**Issue by Anas099X** [thismatters/django-svelte#10]
How to Fix CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

**Comment by thismatters** [comment]
By setting the [`ALLOWED_HOSTS` setting](https://docs.djangoproject.com/en/5.0/ref/settings/#allowed-hosts) to a specific, non-blank value. If you're running a local server then you'll want to set it like:

```py
ALLOWED_HOSTS = ["localhost:8000"]
```

If you're running the demo project then the settings file is found at `demo_project/django_svelte_demo/django_svelte_demo/settings/base.py`.
