### ISSUE TITLE
Bug: Does not import CSS rendered during `npm run build`

### ISSUE THREAD

**Issue by dmgolembiowski** [thismatters/django-svelte#2]
#### Expected behavior:
After running [`npm run build`](https://github.com/thismatters/django-svelte-template/blob/master/package.json#L5), the Django/Jinja template renders 
[`"css_bundle_url": staticfiles_storage.url(f"{app_name}.css")`](https://github.com/thismatters/django-svelte/blob/master/django_svelte/templatetags/django_svelte.py#L15). This is probably a good catch-all for many scenarios, but makes things appear off from the missing CSS generated during rollup.

#### Demo:
![Demonstration](https://i.imgur.com/wo183tx.png)

**Comment by thismatters** [comment]
Hi! Thanks for the pull request and sorry for taking so long to start looking into this issue.

Is `bundle.css` the only css file being output by rollup under your configuration or is it a supplementary bundle meant to accompany the `<app_name>.css` bundle?

**Comment by Ayush-vachhani** [comment]
I got the same issue, it outputs both app.css and app.js.
Any idea how to fix it ?

**Comment by thismatters** [comment]
Version 0.2.0 improves CSS handling. Please have a look!

**Comment by Ayush-vachhani** [comment]
Thanks a lot.
