### ISSUE TITLE
Is this project viable for production?

### ISSUE THREAD

**Issue by Stijn-B** [thismatters/django-svelte#5]
Hi!

We will be using full-stack Django for an upcoming project. I don't want to maintain a separate front-, backend, and API but would love to use some Svelte components in the Django templates for better UI/UX development.

However since the project is not that popular nor active I'm not sure it's responsible to use it for our commercial project. Is anybody using this in a production build and happy with their experience? @thismatters are you building production grade products with this?

If it's close to but not fully production ready we are also open to looking into the possibility of contributing to and maintaining the project.

Thanks for the sharing this cool project!

Kind regards
Stijn

**Comment by thismatters** [comment]
I use this in several of my production operating projects and it seems to be working fine. I have relatively few users, so if you're creating a mass-market tool then it might be beneficial to do some hardening.

I'm totally open to contributions and would welcome other maintainers!

Thank you for your interest.
