### ISSUE TITLE
Hashes for generated js and css

### ISSUE THREAD

**Issue by drimacus182** [thismatters/django-svelte#8]
Is there a way to set up content hashes for generated js and css files? I mean something like `MySpecialComponent.[hash].css` and `MySpecialComponent.[hash].js`?

I understand, that it can be configured in rollup config, but there should be a way `display_svelte` code is aware of this behaviour

**Comment by thismatters** [comment]
It seems like this might be something that the staticfiles stack might be better suited to handle. If I remember correctly [whitenoise](https://whitenoise.readthedocs.io/en/stable/) seems to do something with appending hashes to static files and seamlessly serving them. However whitenoise also has the advantage of being both the hasher and the de-hasher. Is there a good mechanism for the hashed versions of your build to be cataloged for lookup?

**Comment by drimacus182** [comment]
Unfortunately, I'm not familiar with whitenoise and advanced staticfiles configuration. I'm using django-compressor in my setup and was hoping there is a simple way to get hashes for the svelte assets. Anyway, thanks for the reply

**Comment by thismatters** [comment]
Are you still trying to work this out? I've looked at `django-compressor` and it seems possible to support looking up the compressed file, and I don't mind building this in. How would you want to see this behavior accessed? For instance, there could be a setting for `USE_COMPRESSOR`; do you have any other thoughts?

**Comment by drimacus182** [comment]
I lack an understanding of django-compressor's internals to help with this noticeably, but I'm still interested in this feature and would use it if it's available. Any setting of your choice would satisfy me

**Comment by thismatters** [comment]
Cool! I'm working on the next version of this package and will try to support this use case.

**Comment by thismatters** [comment]
I'm trying to get my demo project to use `django-compressor` to compress the JS and CSS bundles, but since those files aren't referenced in a `{% compress %}` tag, `compressor` doesn't compress them! So, they never get a hash. 

Can you provide more detail about how you get `compressor` to actually compress those files?

**Comment by thismatters** [comment]
I'm diving into Svelte 4 for the first time and I'm finding that vite itself wants to add a hash to the filename! Is this the behavior you're running in to and want to incorporate?

**Comment by drimacus182** [comment]
@thismatters It would be great! Thanks for working on this

**Comment by thismatters** [comment]
I just learned about this option in vite which [generates a manifest](https://vitejs.dev/config/build-options.html#build-manifest) of the built files. 

Also in my experimentation I've learned some options in vite that will not include the hash in the filename: 

```
export default defineConfig({
  build: {
    rollupOptions: {
      input: 'src/main.js',
      output: {
        entryFileNames: 'build/main.js',
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === 'style.css') return 'build/main.css';
          return assetInfo.name;
        },
      },

    },
    cssCodeSplit: false,
    sourcemap: true,
  },
  plugins: [
    svelte(),
  ],
})

```

Unfortunately, vite is kinda hostile to one of the main use cases of this package, so I'm going to continue supporting rollup as the bundler of choice; although I will look into parsing the vite manifest as a supported option.

**Comment by thismatters** [comment]
I've figured it all out! Rollup is out, Vite is in. Vite hashes are on their way to being well supported.

If you want to start testing against the branch [spruce-up](https://github.com/thismatters/django-svelte/tree/spruce-up) it should be working. See the new instructions in the readme.

**Comment by thismatters** [comment]
Version 0.2.0 should support the hashed files generated by Vite. The docs indicate how to configure your settings to make this all work. I'm going to close this issue, please feel free to open another one if you run into problems with the new version or the docs are unclear.
